### PR TITLE
add pid_status feature

### PR DESCRIPTION
**Pull request by marcvs**
## Description:

**Related issue (if applicable):** fixes #<Sonoff-Tasmota issue number goes here>

## Checklist:
  - [ ] The pull request is done against the latest dev branch
  - [x] Only relevant files were touched
  - [x] Only one feature/fix was added per PR.
  - [ ] The code change is tested and works on core 2.3.0, 2.4.2, 2.5.2, and pre-2.6
  - [ ] The code change pass travis tests. **Your PR cannot be merged unless tests pass**
  - [x] I accept the [CLA](https://github.com/arendst/Sonoff-Tasmota/blob/development/CONTRIBUTING.md#contributor-license-agreement-cla).

### CODE REVIEW

**Comment by marcvs** [comment]
Now that I start playing with it, I wonder whether it is maybe smarter to return the values differently, i.e. not in the LOGGING.  One example could be to use the json in the /PID output.

Any feeling on this?

**Comment by colinl** [comment]
Sorry about the delay, have been busy on other things.
I am not in a position to be able to build and test the mods at the moment, am I right in thinking that what you have done shows the data in the log, but does not send it back via MQTT?
I think the enhancement request was for the values to be returned via MQTT.  What you have done is certainly useful but I think it would be more useful via MQTT.

**Comment by marcvs** [comment]
Well, the logs are also returned via MQTT.

When I'll find some time, I'll turn this into a json response.

**Comment by colinl** [comment]
Oh, are they? I don't think I knew that,   what mqtt topic do the logs appear on?

**Comment by marcvs** [comment]
They appear on the /LOGGING topic.

I use this commandline for get_pid_status.sh:

```
echo "" | mosquitto_pub -q 1 -h q -l -t /sensor/5/cmnd/pid_status
mosquitto_sub -q 1 -h q -t /sensor/5/LOGGING -C 13
```

**Comment by colinl** [comment]
Following research I see that there is a command (MqttLog) to enable that.  How had I missed that I wonder.
However, as you have suggested, it would be better as a JSON value so it can be picked up and analysed more easily by other applications.  I suppose this could either be on a separate topic or could be added in to the PID topic. It would not want to be in PID every time though as that would be an overhead that would not normally be wanted.  Possibly a separate topic would be better, what do you think @marcvs?

**Comment by marcvs** [comment]
I was considering the PID topic, but that might confuse clients that
expect a specific json, so PID_STATUS (all caps?) could be another valid
choice.

**Comment by marcvs** [comment]
Sorry, I have to face the truth: I'll not be able to finish this anytime soom.

**Pull request closed without merging**
